# Generated by Django 4.2.2 on 2023-06-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='event_title',
            field=models.CharField(default='Заголовок', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.eventtemplate'),
        ),
    ]
