# Generated by Django 4.2.2 on 2023-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
